<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="nagendra-ThinkPad-X220" ignored="0" name="Test" tests="15" failures="3" timestamp="03 Jun 2018 10:31:02 GMT" time="0.127" errors="0">
  <testcase name="test" time="0.015" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.002" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.002" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- test -->
  <testcase name="test" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.example.retryFailedTestcases.ExampleTestFailure.test(ExampleTestFailure.java:9)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test -->
  <testcase name="testOne" time="0.004" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase name="testOne" time="0.002" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase name="testOne" time="0.002" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase name="testOne" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testOne -->
  <testcase name="testOne" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at com.example.retryFailedTestcases.ExampleTestFailure.testOne(ExampleTestFailure.java:14)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testOne -->
  <testcase name="testTwo" time="0.002" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase name="testTwo" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase name="testTwo" time="0.003" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase name="testTwo" time="0.001" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <skipped/>
  </testcase> <!-- testTwo -->
  <testcase name="testTwo" time="0.006" classname="com.example.retryFailedTestcases.ExampleTestFailure">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.example.retryFailedTestcases.ExampleTestFailure.testTwo(ExampleTestFailure.java:19)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- testTwo -->
</testsuite> <!-- Test -->
